### ISSUE TITLE
.

### ISSUE THREAD

**Issue by AzizStark** [kishan0725/Foodie#1]

**Comment by kishan0725** [comment]
> You are not supposed to upload my code to an individual repository without any credits to me. You can only fork it as per Github's DMCA.
> 
> Please remove this or either to be reported to Github's DMCA takedown:
> https://help.github.com/en/github/site-policy/dmca-takedown-policy
> 
> Also, I have included GNU license.

Hey dude, You and I are the same batch of ReactJS Workshop. If you use print statements in your code to print something, that doesn't mean no one should use print in their code. I don't see any plagiarism in my code, except that 'LoginPage' which I created during the workshop itself. And you uploaded the GNU LICENSE yesterday itself, but I upload my repository nearly a month ago. So, please think twice before you create an issue and insults someone's hard work. Hope you understand. Have a great day!
